### ISSUE TITLE
See referral traffic for inbound analysis

### ISSUE THREAD

**Issue by median-man** [median-man/project-1-demo#1]
## User Story
AS a marketing analyst
I WANT to see referral traffic
SO THAT I can adapt strategy to convert more leads

## Acceptance criteria
GIVEN I am an authenticated user
WHEN I request a range of referral traffic
THEN a chart is generated

## Tasks

- [ ] create a login page
- [ ] create a form page with inputs for date range
- [ ] create static page as a prototype for a referrals chart
- [ ] write function to dynamically generate a chart from a given date range
